github:
  description: "Apache Fineract"
  homepage: https://fineract.apache.org
  labels:
    - apache
    - banking
    - finance
    - fintech
    - group-lending
    - group-savings
    - java
    - lending
    - loans
    - microfinance
    - savings
    - social-impact
    - tech4good
  enabled_merge_buttons:
    merge: true
    squash: false
    rebase: false
  rulesets:
    - name: "Branch Protection"
      type: branch
      branches:
        includes:
          - "develop"
          - "release/*"
          - "maintenance/*"
          # temporary (to test protections below)
          - "protected-branch-test"
      restrict_deletion: true
      restrict_force_push: true
      required_signatures: true
      required_linear_history: false
      required_conversation_resolution: true
notifications:
  commits: commits@fineract.apache.org
  pullrequests: issues@fineract.apache.org
